language: php

php:
  - 7.2

cache:
  directories:
    - vendor

install:
  - sudo apt-get update
  - sudo apt-get install libssh2-1-dev anisble
  - echo "extension=ssh2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test -- --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)