language: php

php:
  - 7.2

install:
  - pecl install ssh2
  - echo "extension=ssh2.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test -- --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)